### ISSUE TITLE
Carousel does not rerender when state  pass to prop slides changes.

### ISSUE THREAD

**Issue by duongthienlee** [suhailsulu/react-carousel-3d#1]
So I have a state contains array of objects which I pass to carousel. When the state changes, the carousel does not re-render.

**Comment by suhailsulu** [comment]
@duongthienlee Sorry for the late reply, can you create a sample code in [https://jsfiddle.net/](https://jsfiddle.net/) or somewhere else so that i can review the code

**Comment by suhailsulu** [comment]
@duongthienlee fixed the issue regarding the rerendering. 
The position of the button depends upon the height of the active slide, that's why its changes when slide is changed
