### ISSUE TITLE
Not working with Next Js

### ISSUE THREAD

**Issue by Deba22** [suhailsulu/react-carousel-3d#21]
Hi,

I get the below error when I use it in Next Js project
```
`ReferenceError: window is not defined`
at Object.<anonymous> (C:\Deba\Workspace2021\Nextjs\myportfolio\node_modules\3d-react-carousal\dist\index.js:1:255)
```

**Comment by suhailsulu** [comment]
This library is not developed to support SSR, It wont work in Next Js if you use SSR. Will update support for SSR in the future.

**Comment by Deba22** [comment]
ok. Got it. Thanks.
I was now trying to use it using dynamic imports with no SSR https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr. Need to figure it out how to make it work with dynamic imports.

**Comment by Deba22** [comment]
Got it working in Next Js using dynamic imports with no SSR https://stackoverflow.com/questions/66842447/next-js-dynamic-imports-with-no-ssr-not-working. The library is working great. Thanks for the amazing library.
