### ISSUE TITLE
Module parse failed: Unexpected token (180:4) - Need an appropriate loader to handle this file type...

### ISSUE THREAD

**Issue by Airrudi** [suhailsulu/react-carousel-3d#43]
Hi,

I just installed the plugin, setup the basic slides and the <Carousel> element.
When I run the application, it throws the error below (NextJS):

./node_modules/3d-react-carousal/src/index.js 180:4
Module parse failed: Unexpected token (180:4)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
|   return (
>     <div className="react-3d-carousel" style={{ height }} {...handlers}>
|           {slides && slides.length > 0
|                 && <div className="slider-container" >

Can you help me out?

Thanks!

**Comment by suhailsulu** [comment]
https://stackoverflow.com/questions/58562201/how-to-fix-you-may-need-an-appropriate-loader-to-handle-this-file-type-currentl
