### ISSUE TITLE
failed on build

### ISSUE THREAD

**Issue by randyviandaputra** [suhailsulu/react-carousel-3d#5]
I found some errors during the build, 
I using react 16.7.0

![image](https://user-images.githubusercontent.com/12962273/50957665-6b37be80-14f1-11e9-835e-d9662507b1a1.png)

**Comment by suhailsulu** [comment]
I build using react 16.7.0 running command 'yarn run build' and it builds successfully.

![image](https://user-images.githubusercontent.com/15671227/50959411-e8ab0100-14e8-11e9-84f0-0303439b49f6.png)

Did you used this library in any other project or just buid this library?

**Comment by randyviandaputra** [comment]
I use it with Gatsby

**Comment by randyviandaputra** [comment]
> in other projet , I use it with Gatsby

**Comment by suhailsulu** [comment]
check this https://github.com/gatsbyjs/gatsby/issues/309

**Comment by suhailsulu** [comment]
Also this https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-code-classlanguage-textwindowcode-is-defined

**Comment by randyviandaputra** [comment]
> Also this https://www.gatsbyjs.org/docs/debugging-html-builds/#how-to-check-if-code-classlanguage-textwindowcode-is-defined

I use it this way, it's the same, but the error is different

**Comment by suhailsulu** [comment]
Can you show me the code how are you importing the library.  When i googled your error its seems like issue in importing libraries

**Comment by randyviandaputra** [comment]
> Can you show me the code how are you importing the library. When i googled your error its seems like issue in importing libraries

![image](https://user-images.githubusercontent.com/12962273/50968191-e6f33480-150c-11e9-849b-385ae3dbaf40.png)

**Comment by suhailsulu** [comment]
![image](https://user-images.githubusercontent.com/15671227/50969659-32a1e000-1505-11e9-8ef3-7b49e67a47f0.png)

**Comment by randyviandaputra** [comment]
thanks solved, i check window if not undefined on component
